version: '3.0'
services:
  db:
    build: ./build/postgres
    ports:
      - "5432:5432"
  app:
    build:
      context: .
      dockerfile: ./build/app/Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"