# Generated by Django 2.1.7 on 2019-05-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0002_person_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='twitter',
            field=models.CharField(blank=True, help_text='Please do not include the @ symbol.', max_length=140, null=True, verbose_name='Twitter'),
        ),
    ]
