# Generated by Django 2.1.7 on 2019-05-22 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sources', '0003_update_source_fields_help_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, help_text='This is when the item was updated in the system.', null=True, verbose_name='Updated in system')),
                ('date_time', models.DateTimeField(help_text='When the interaction took place', verbose_name='When?')),
                ('interaction_type', models.CharField(blank=True, choices=[('email', 'Email'), ('inperson', 'In-person'), ('telephone', 'Telephone')], max_length=255, verbose_name='Type')),
                ('notes', models.TextField(blank=True, help_text='Add any notes about interaction that may be helpful to you or others in the future.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_person_interaction', to=settings.AUTH_USER_MODEL)),
                ('interviewee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviee', to='sources.Person', verbose_name='Interviewee')),
                ('interviewer', models.ManyToManyField(related_name='interviewer', to=settings.AUTH_USER_MODEL, verbose_name='Interviewer(s)')),
            ],
            options={
                'verbose_name': 'Interaction',
                'verbose_name_plural': 'Interactions',
            },
        ),
    ]
