# Generated by Django 2.1.7 on 2019-05-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0004_add_interaction_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='private',
            field=models.BooleanField(blank=True, default=True, help_text='Private sources will only be visible to you. Non-private sources will be visible to all newsroom users.'),
        ),
    ]
