# Generated by Django 2.2.1 on 2019-05-28 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0006_remove_required_status_from_many_person_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interaction',
            options={'ordering': ['-date_time'], 'verbose_name': 'Interaction', 'verbose_name_plural': 'Interactions'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['-updated'], 'verbose_name': 'Person', 'verbose_name_plural': 'People'},
        ),
    ]
