# Generated by Django 2.2.2 on 2019-06-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0011_add_verbose_name_for_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, help_text='This is when the item was updated in the system.', null=True, verbose_name='Updated in system')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Industry name')),
            ],
            options={
                'verbose_name_plural': 'Industries',
            },
        ),
        migrations.AddField(
            model_name='person',
            name='linkedin',
            field=models.URLField(blank=True, help_text='Please include http:// at the beginning.', max_length=255, null=True, verbose_name='LinkedIn URL'),
        ),
        migrations.RemoveField(
            model_name='person',
            name='organization',
        ),
        migrations.AddField(
            model_name='person',
            name='organization',
            field=models.ManyToManyField(blank=True, to='sources.Organization'),
        ),
        migrations.AlterField(
            model_name='person',
            name='private',
            field=models.BooleanField(blank=True, default=False, help_text='Private sources will only be visible to you. Non-private sources will be visible to all newsroom users.'),
        ),
        migrations.AddField(
            model_name='person',
            name='industries',
            field=models.ManyToManyField(blank=True, to='sources.Industry'),
        ),
    ]
