# Generated by Django 2.2.3 on 2019-07-26 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0013_person_privacy_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='private',
        ),
    ]
