# Generated by Django 2.2.3 on 2019-07-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0014_remove_person_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='privacy_level',
            field=models.CharField(choices=[('public', 'Public (whole newsroom)'), ('searchable', 'Semi-private (searchable by newsroom)'), ('private_individual', 'Private (only me)')], default='public', help_text='Who has access to view? Searchable (semi-private) means the general information is available, but not the details.', max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='privacy_level',
            field=models.CharField(choices=[('public', 'Public (whole newsroom)'), ('searchable', 'Semi-private (searchable by newsroom)'), ('private_individual', 'Private (only me)')], default='public', help_text='Who has access to view? Searchable (semi-private) means the general information is available, but not the details.', max_length=255),
        ),
    ]
