# Generated by Django 2.2.3 on 2019-09-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0015_privacy_mixin_and_new_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='privacy_level',
            field=models.CharField(choices=[('public', 'Public (whole newsroom)'), ('searchable', 'Semi-private (searchable by newsroom)'), ('private_individual', 'Private (only me)')], help_text='Who has access to view? Searchable (semi-private) means the general information is available, but not certain details.', max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='privacy_level',
            field=models.CharField(choices=[('public', 'Public (whole newsroom)'), ('searchable', 'Semi-private (searchable by newsroom)'), ('private_individual', 'Private (only me)')], help_text='Who has access to view? Searchable (semi-private) means the general information is available, but not certain details.', max_length=255),
        ),
    ]
