# Generated by Django 2.2.3 on 2019-10-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0016_privacy_default_to_empty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertise',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Type of expertise'),
        ),
        migrations.AlterField(
            model_name='industry',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Industry name'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Organization name'),
        ),
    ]
