# Generated by Django 2.2.8 on 2019-12-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0017_update_name_field_on_expertise_industry_organization_to_be_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='middle_name',
        ),
        migrations.AddField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
