# Generated by Django 2.2.8 on 2019-12-16 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0018_update_source_to_use_full_name_field_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertise',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Type of expertise'),
        ),
        migrations.AlterField(
            model_name='industry',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Industry name'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Organization name'),
        ),
    ]
