# Generated by Django 2.2.9 on 2020-02-11 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0020_update_timezone_to_use_pytz_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='gatekeeper',
            field=models.BooleanField(blank=True, default=False, help_text='Is this person the contact for another source?'),
        ),
    ]
