# Generated by Django 2.2.9 on 2020-02-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0022_add_dive_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='owned_by',
            field=models.ManyToManyField(blank=True, help_text='These are the dives that have ownership of this source.', related_name='dive_owner', to='sources.Dive'),
        ),
    ]
