# Generated by Django 2.2.10 on 2020-02-24 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0023_add_person_owned_by_field_for_dive_relationship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='owned_by',
        ),
        migrations.AddField(
            model_name='person',
            name='exportable_by',
            field=models.ManyToManyField(blank=True, help_text='These are the dives that can export this source.', related_name='dive_owner', to='sources.Dive'),
        ),
    ]
