# Generated by Django 3.0.4 on 2020-03-05 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0024_rename_owned_by_to_exportable_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='prefix',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Prefix'),
        ),
    ]
