# Generated by Django 3.0.4 on 2020-03-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0025_change_prefix_to_free_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='organization_additional',
            field=models.ManyToManyField(blank=True, related_name='additional_affiliations', to='sources.Organization', verbose_name='Additional affiliations'),
        ),
        migrations.AlterField(
            model_name='person',
            name='organization',
            field=models.ManyToManyField(blank=True, to='sources.Organization', verbose_name='Organization (primary)'),
        ),
    ]
