# Generated by Django 3.0.4 on 2020-03-06 16:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sources', '0025_change_prefix_to_free_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='exportable_by',
        ),
        migrations.AddField(
            model_name='person',
            name='exportable_by_dive',
            field=models.ManyToManyField(blank=True, help_text='These are the dives that can export this source.', related_name='exportable_dive', to='sources.Dive', verbose_name='Exportable by (Dive)'),
        ),
        migrations.AddField(
            model_name='person',
            name='exportable_by_user',
            field=models.ManyToManyField(blank=True, help_text='These are the users who can export this source.', related_name='exportable_user', to=settings.AUTH_USER_MODEL, verbose_name='Exportable by (User)'),
        ),
    ]

