# Generated by Django 3.0.4 on 2020-05-27 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0026_rename_notes_to_import_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='language',
        ),
    ]
